import { NextResponse } from "next/server";
import { z } from "zod";
import { reproduceHistoricalCalculation } from "@carbonloop/carbon-engine";
import { requireHistoricalFactorSnapshot } from "@carbonloop/factor-registry";
import { appendQuestTransition, simulateWalkingActivity } from "@carbonloop/quest-engine";
import { appendScoreEvent, deriveLevel, deriveScoreBalances, deriveStreak } from "@carbonloop/scoring";
import { appendRedemptionEvent, seededMockCanteenReward } from "@carbonloop/marketplace";

type TruthLabel = "SIMULATED_DEMO_ONLY" | "SYNTHETIC_TEST_ONLY" | "MOCK_DEMO_ONLY" | "PROJECTED" | "VERIFIED";
const labels: TruthLabel[] = ["SIMULATED_DEMO_ONLY", "SYNTHETIC_TEST_ONLY", "MOCK_DEMO_ONLY"];
const now = "2026-08-28T00:00:00.000Z";
let sequence = 0;
const id = (prefix: string) => `${prefix}_${++sequence}`;
const runs = new Map<string, { questRunId: string; questType: "walk_instead_of_ride" | "shuttle_journey"; state: "active" | "completed"; history: any[]; completedAt?: string }>();
const usedTokens = new Set<string>();
const idempotent = new Map<string, unknown>();
let scoreHistory: any[] = [];
const redemptions = new Map<string, { redemptionId: string; history: any[] }>();
const resetResponseSchema = z.object({ reset: z.literal("SIMULATED_DEMO_ONLY"), persistence: z.literal("SIMULATED_DEMO_ONLY process-local repository reset; not production persistence"), truthLabels: z.array(z.string()).min(1) });

const factor = (activityType: string, decimalValue: string) => ({ factorId: `SYNTHETIC_TEST_ONLY_${activityType}_factor`, versionId: `SYNTHETIC_TEST_ONLY_${activityType}_v1`, category: "transport", activityType, quantityUnit: "km", factorUnit: "kgCO2e/km", decimalValue, sourceTitle: "SYNTHETIC_TEST_ONLY demo factor", sourcePublisher: "SYNTHETIC_TEST_ONLY", sourceReference: "SYNTHETIC_TEST_ONLY", geography: "SYNTHETIC_TEST_ONLY", dataLabel: "SYNTHETIC_TEST_ONLY", methodologyVersion: "SYNTHETIC_TEST_ONLY_v1", effectiveFrom: "2026-01-01", qualityLabel: "synthetic", uncertainty: "synthetic", createdAt: now });
const motorbikeFactor = requireHistoricalFactorSnapshot(factor("motorbike", "0.100"));
const walkingFactor = requireHistoricalFactorSnapshot(factor("walking", "0.000"));

function response(data: Record<string, unknown>, status = 200) { return NextResponse.json({ ...data, truthLabels: data.truthLabels ?? labels }, { status }); }
function requestId(request: Request) { return request.headers.get("x-request-id") ?? crypto.randomUUID(); }
function error(request: Request, code: string, message: string, status: number) { return response({ code, message, requestId: requestId(request) }, status); }
async function body<T>(request: Request, schema: z.ZodType<T>): Promise<T | NextResponse> { try { return schema.parse(await request.json()); } catch { return error(request, "VALIDATION_ERROR", "Request body does not match the demo API contract.", 400); } }
function key(request: Request): string | NextResponse { const value = request.headers.get("idempotency-key"); return value?.trim() ? value : error(request, "IDEMPOTENCY_KEY_REQUIRED", "An Idempotency-Key header is required for demo writes.", 400); }
function appendScore(event: any) { const result = appendScoreEvent(scoreHistory, event); if (result.status === "rejected") throw new Error(result.reason); scoreHistory = [...result.history]; }
appendScore({ eventId: "SYNTHETIC_TEST_ONLY_seed_green", questRunId: "SYNTHETIC_TEST_ONLY_seed_run", occurredAt: now, idempotencyKey: "SYNTHETIC_TEST_ONLY_seed_green", type: "green_points_issued", amount: 10, calculationId: "SYNTHETIC_TEST_ONLY_seed_calculation", evidenceTier: "V2", activityType: "walking", avoidedKgCo2e: "2.500000", carbonResultStatus: "calculated" });
function resetRepository() { sequence = 0; runs.clear(); usedTokens.clear(); idempotent.clear(); redemptions.clear(); scoreHistory = []; appendScore({ eventId: "SYNTHETIC_TEST_ONLY_seed_green", questRunId: "SYNTHETIC_TEST_ONLY_seed_run", occurredAt: now, idempotencyKey: "SYNTHETIC_TEST_ONLY_seed_green", type: "green_points_issued", amount: 10, calculationId: "SYNTHETIC_TEST_ONLY_seed_calculation", evidenceTier: "V2", activityType: "walking", avoidedKgCo2e: "2.500000", carbonResultStatus: "calculated" }); }

function calculation(runId: string, distanceKm: string, evidenceTier: "V1" | "V2") {
  return reproduceHistoricalCalculation({ calculationId: id("synthetic_calculation"), activityType: "walking", baseline: { baselineId: "SYNTHETIC_TEST_ONLY_motorbike_baseline", kind: "seeded_demonstration", quantity: distanceKm, unit: "km", dataLabel: "SYNTHETIC_TEST_ONLY", declaredAt: now, displacedMotorizedBaseline: true, truthLabels: ["seeded", "simulated"] }, actualQuantity: distanceKm, actualUnit: "km", evidenceTier, truthLabels: ["seeded", "simulated"], calculatedAt: now, baselineFactorSnapshot: motorbikeFactor, actualFactorSnapshot: walkingFactor });
}

export async function health() { return response({ status: "ok", persistence: "SIMULATED_DEMO_ONLY process-local repository; not production persistence" }); }
export async function reset(request: Request) { const parsed = await body(request, z.object({}).strict()); if (parsed instanceof NextResponse) return parsed; const k = key(request); if (k instanceof NextResponse) return k; resetRepository(); return NextResponse.json(resetResponseSchema.parse({ reset: "SIMULATED_DEMO_ONLY", persistence: "SIMULATED_DEMO_ONLY process-local repository reset; not production persistence", truthLabels: labels })); }
export async function quests() { return response({ quests: [{ questTemplateId: "SIMULATED_DEMO_ONLY_walk_quest", title: "SIMULATED_DEMO_ONLY Walk Instead of Ride", type: "walk_instead_of_ride" }, { questTemplateId: "SIMULATED_DEMO_ONLY_shuttle_quest", title: "SIMULATED_DEMO_ONLY Shuttle Journey", type: "shuttle_journey" }] }); }
export async function createRun(request: Request) { const parsed = await body(request, z.object({ questTemplateId: z.enum(["SIMULATED_DEMO_ONLY_walk_quest", "SIMULATED_DEMO_ONLY_shuttle_quest"]) })); if (parsed instanceof NextResponse) return parsed; const k = key(request); if (k instanceof NextResponse) return k; const saved = idempotent.get(k); if (saved) return response(saved as Record<string, unknown>); const questRunId = id("SIMULATED_DEMO_ONLY_run"); const questType = parsed.questTemplateId.includes("walk") ? "walk_instead_of_ride" : "shuttle_journey" as const; const event = { eventId: id("quest_event"), questRunId, questType, from: "available" as const, to: "active" as const, occurredAt: now, idempotencyKey: `${k}-transition` }; const transition = appendQuestTransition([], event); if (transition.status === "rejected") return error(request, "QUEST_TRANSITION_REJECTED", transition.reason, 409); runs.set(questRunId, { questRunId, questType, state: "active", history: [...transition.history] }); const result = { questRun: { questRunId, questType, state: "active", recordLabel: "SIMULATED_DEMO_ONLY" } }; idempotent.set(k, result); return response(result, 201); }
export async function completeRun(request: Request, questRunId: string) { const parsed = await body(request, z.object({ distanceKm: z.string().regex(/^\d+(?:\.\d+)?$/), replacedMotorizedBaseline: z.boolean() })); if (parsed instanceof NextResponse) return parsed; const k = key(request); if (k instanceof NextResponse) return k; const run = runs.get(questRunId); if (!run) return error(request, "QUEST_RUN_NOT_FOUND", "The simulated quest run does not exist.", 404); if (run.state === "completed") return error(request, "QUEST_ALREADY_COMPLETED", "The simulated quest run is already complete.", 409); const activity = simulateWalkingActivity({ questRunId, occurredAt: now, distanceKm: parsed.distanceKm }); const transition = appendQuestTransition(run.history, { eventId: id("quest_event"), questRunId, questType: run.questType, from: "active", to: "completed", occurredAt: now, idempotencyKey: k }); if (transition.status === "rejected") return error(request, "QUEST_TRANSITION_REJECTED", transition.reason, 409); run.history = [...transition.history]; run.state = "completed"; run.completedAt = now; const result = parsed.replacedMotorizedBaseline ? calculation(questRunId, parsed.distanceKm, "V2") : undefined; appendScore({ eventId: id("xp"), questRunId, occurredAt: now, idempotencyKey: `${k}-xp`, type: "eco_xp_issued", amount: 25, mission: { questRunId, questType: run.questType, state: "completed", completedAt: now } }); let greenPointsIssued = 0; if (result?.status === "calculated" && Number(result.avoidedKgCo2e) > 0) { greenPointsIssued = Math.max(1, Math.floor(Number(result.avoidedKgCo2e) * 4)); appendScore({ eventId: id("green"), questRunId, occurredAt: now, idempotencyKey: `${k}-green`, type: "green_points_issued", amount: greenPointsIssued, calculationId: result.calculationId, evidenceTier: "V2", activityType: "walking", avoidedKgCo2e: result.avoidedKgCo2e, carbonResultStatus: "calculated" }); } return response({ questRun: { ...run, recordLabel: "SIMULATED_DEMO_ONLY" }, activity, carbonResult: result, greenPointsIssued }); }
export async function shuttle(request: Request) { const parsed = await body(request, z.object({ token: z.literal("SIMULATED_DEMO_ONLY_shuttle_token_one") })); if (parsed instanceof NextResponse) return parsed; const k = key(request); if (k instanceof NextResponse) return k; if (usedTokens.has(parsed.token)) return error(request, "SHUTTLE_TOKEN_REPLAYED", "The synthetic demo shuttle token was already used.", 409); usedTokens.add(parsed.token); const questRunId = id("SIMULATED_DEMO_ONLY_shuttle_run"); const result = calculation(questRunId, "2.0", "V1"); let points = 0; if (result.status === "calculated") { points = Math.max(1, Math.floor(Number(result.avoidedKgCo2e) * 4)); appendScore({ eventId: id("green"), questRunId, occurredAt: now, idempotencyKey: `${k}-green`, type: "green_points_issued", amount: points, calculationId: result.calculationId, evidenceTier: "V1", activityType: "shuttle", avoidedKgCo2e: result.avoidedKgCo2e, carbonResultStatus: "calculated" }); } return response({ evidence: { evidenceId: id("SIMULATED_DEMO_ONLY_evidence"), tier: "V1", source: "synthetic_demo_token", verificationLabel: "VERIFIED", recordLabel: "SIMULATED_DEMO_ONLY" }, carbonResult: result, greenPointsIssued: points, truthLabels: [...labels, "VERIFIED"] }); }
export async function progress() { const balances = deriveScoreBalances(scoreHistory); return response({ player: { playerId: "SYNTHETIC_TEST_ONLY_player", recordLabel: "SYNTHETIC_TEST_ONLY" }, progress: { level: deriveLevel(balances.ecoXp), streakDays: deriveStreak([...runs.values()].filter((run) => run.state === "completed").map((run) => ({ completedAt: run.completedAt!, eligible: true }))), greenPoints: balances.greenPoints } }); }
export async function ledger() { return response({ events: scoreHistory, balances: deriveScoreBalances(scoreHistory), ledgerLabel: "SIMULATED_DEMO_ONLY append-only" }); }
export async function catalogue() { return response({ rewards: [{ ...seededMockCanteenReward, recordLabel: "MOCK_DEMO_ONLY" }] }); }
export async function redeem(request: Request) { const parsed = await body(request, z.object({ rewardItemId: z.literal("SYNTHETIC_TEST_ONLY_canteen_reward") })); if (parsed instanceof NextResponse) return parsed; const k = key(request); if (k instanceof NextResponse) return k; const known = redemptions.get(k); if (known) return response({ redemption: { redemptionId: known.redemptionId, state: "reserved", recordLabel: "MOCK_DEMO_ONLY" }, idempotent: true }); const balances = deriveScoreBalances(scoreHistory); if (balances.greenPoints < seededMockCanteenReward.greenPointsCost) return error(request, "INSUFFICIENT_GREEN_POINTS", "Synthetic demo balance is insufficient for this mock reward.", 409); const redemptionId = id("MOCK_DEMO_ONLY_redemption"); const event = { eventId: id("redemption_event"), redemptionId, rewardItemId: parsed.rewardItemId, from: "available" as const, to: "reserved" as const, occurredAt: now, idempotencyKey: k, fulfilmentLabel: "MOCK_DEMO_ONLY" as const }; const appended = appendRedemptionEvent([], event); if (appended.status === "rejected") return error(request, "REDEMPTION_REJECTED", appended.reason, 409); redemptions.set(k, { redemptionId, history: [...appended.history] }); return response({ redemption: { redemptionId, state: appended.state, recordLabel: "MOCK_DEMO_ONLY", fulfilment: "MOCK_DEMO_ONLY no payment or delivery" } }, 201); }
export async function campus() { return response({ aggregate: { campusId: "SYNTHETIC_TEST_ONLY_campus", privacyThresholdApplied: true, minimumCohort: "SYNTHETIC_TEST_ONLY", metrics: { syntheticEligibleJourneys: scoreHistory.length }, evidenceQuality: { V1: scoreHistory.length, V2: 0, V3: 0, V4: 0 }, recordLabel: "SYNTHETIC_TEST_ONLY" } }); }
