import { describe, expect, it } from "vitest";
import type { CarbonCalculationResult } from "@carbonloop/carbon-engine";
import { SYNTHETIC_TEST_ONLY, appendScoreEvent, canIssueGreenPoints, deriveLevel, deriveScoreBalances, deriveStreak, deriveTeamContribution, syntheticConversionRateSchema, syntheticDemoConversionRate } from "../src/index.js";
const completion = { questRunId: "SYNTHETIC_TEST_ONLY_run", questType: "shuttle_journey" as const, state: "completed" as const, completedAt: "2026-08-28T09:00:00.000Z" };
const xp = { eventId: "SYNTHETIC_TEST_ONLY_xp", questRunId: completion.questRunId, occurredAt: "2026-08-28T09:01:00.000Z", idempotencyKey: "SYNTHETIC_TEST_ONLY_xp_key", type: "eco_xp_issued" as const, amount: 120, mission: completion };
const green = { eventId: "SYNTHETIC_TEST_ONLY_green", questRunId: completion.questRunId, occurredAt: "2026-08-28T09:02:00.000Z", idempotencyKey: "SYNTHETIC_TEST_ONLY_green_key", type: "green_points_issued" as const, amount: 4, calculationId: "SYNTHETIC_TEST_ONLY_calculation", evidenceTier: "V1" as const, activityType: "shuttle", avoidedKgCo2e: "1.0", carbonResultStatus: "calculated" as const };
const carbon: CarbonCalculationResult = { status: "calculated", calculationId: "SYNTHETIC_TEST_ONLY_calculation", calculationEngineVersion: "synthetic", calculatedAt: "2026-08-28T09:00:00.000Z", rounding: "synthetic", baselineSnapshot: {} as never, baselineFactorSnapshot: {} as never, actualFactorSnapshot: {} as never, evidenceTier: "V1", truthLabels: ["simulated"], baselineKgCo2e: "2.0", actualKgCo2e: "1.0", avoidedKgCo2e: "1.0" };
describe("scoring and progression", () => {
  it("issues Eco XP only for completed missions and is idempotent", () => { const first = appendScoreEvent([], xp); expect(first.status).toBe("appended"); const duplicate = appendScoreEvent(first.status === "appended" ? first.history : [], xp); expect(duplicate.status).toBe("idempotent"); });
  it("allows Green Points only for eligible evidence-backed carbon, never exercise alone", () => { expect(canIssueGreenPoints(carbon, "shuttle")).toBe(true); expect(canIssueGreenPoints(carbon, "exercise")).toBe(false); expect(syntheticConversionRateSchema.parse(syntheticDemoConversionRate).dataLabel).toBe(SYNTHETIC_TEST_ONLY); expect(appendScoreEvent([], { ...green, activityType: "exercise" })).toMatchObject({ status: "rejected" }); });
  it("uses append-only reversal instead of deletion", () => { const reversal = { eventId: "SYNTHETIC_TEST_ONLY_reverse", questRunId: completion.questRunId, occurredAt: "2026-08-28T09:03:00.000Z", idempotencyKey: "SYNTHETIC_TEST_ONLY_reverse_key", type: "green_points_reversed" as const, reversalOfEventId: green.eventId, reason: "SYNTHETIC_TEST_ONLY correction" }; const result = appendScoreEvent([xp, green], reversal); expect(result.status).toBe("appended"); expect(deriveScoreBalances(result.status === "appended" ? result.history : []).greenPoints).toBe(0); });
  it("derives levels, current eligible streaks, and aggregate-only team contribution", () => { expect(deriveLevel(250)).toBe(3); expect(deriveStreak([{ completedAt: "2026-08-26T09:00:00.000Z", eligible: true }, { completedAt: "2026-08-27T09:00:00.000Z", eligible: true }, { completedAt: "2026-08-28T09:00:00.000Z", eligible: true }])).toBe(3); expect(deriveTeamContribution([{ teamId: "SYNTHETIC_TEST_ONLY_team", missionDate: "2026-08-28", eligibleMissionCount: 1 }])).toEqual([{ teamId: "SYNTHETIC_TEST_ONLY_team", eligibleMissionCount: 1 }]); });
});